workflows:
  ios-weatherapp:
    name: iOS WeatherApp Local Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "WeatherApp.xcodeproj"
        XCODE_SCHEME: "WeatherApp"
        BUNDLE_ID: "com.example.weatherapp" # Replace with your bundle ID
      ios_signing:
        provisioning_profiles:
          - WeatherApp_Dev_Profile        # Upload this profile in Codemagic

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Set build number
        script: |
          echo "Updating build number..."
          cd $CM_BUILD_DIR
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      - name: Build WeatherApp
        script: |
          echo "Building .xcarchive..."
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$CM_BUILD_DIR/build/WeatherApp.xcarchive" \
            -sdk iphoneos \
            -configuration Release \
            clean archive \
            DEVELOPMENT_TEAM="$CM_DEVELOPER_TEAM" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="WeatherApp_Dev_Profile"

      - name: Export unsigned .ipa
        script: |
          echo "Exporting .ipa file..."
          mkdir -p $CM_BUILD_DIR/build/ipa
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/WeatherApp.xcarchive" \
            -exportOptionsPlist <(cat <<EOF
            {
              "method": "development",
              "signingStyle": "manual",
              "compileBitcode": false,
              "destination": "export",
              "stripSwiftSymbols": true,
              "thinning": "<none>"
            }
          EOF
          ) \
          -exportPath "$CM_BUILD_DIR/build/ipa"

    artifacts:
      - build/ipa/*.ipa
      - build/WeatherApp.xcarchive

    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true
