workflows:
  ios-weatherapp:
    name: iOS WeatherApp Unsigned Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "WeatherApp.xcodeproj"
        XCODE_SCHEME: "WeatherApp"
        BUNDLE_ID: "com.example.weatherapp"

      # ✅ Disable signing entirely
      ios_signing: null

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Set build number
        script: |
          echo "Updating build number..."
          cd $CM_BUILD_DIR
          agvtool new-version -all $(($BUILD_NUMBER + 1))

      - name: Build for iOS Simulator (No Signing)
        script: |
          echo "Building for simulator..."
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Archive Unsigned Build
        script: |
          echo "Archiving unsigned build..."
          mkdir -p $CM_BUILD_DIR/build/unsigned
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/WeatherApp.xcarchive" \
            CODE_SIGNING_ALLOWED=NO \
            clean archive

      - name: Export Unsigned .ipa
        script: |
          echo "Exporting unsigned .ipa..."
          mkdir -p $CM_BUILD_DIR/build/ipa
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/WeatherApp.xcarchive" \
            -exportOptionsPlist <(cat <<EOF
            {
              "method": "development",
              "signingStyle": "manual",
              "compileBitcode": false,
              "stripSwiftSymbols": true,
              "destination": "export",
              "thinning": "<none>"
            }
          EOF
          ) \
          -exportPath "$CM_BUILD_DIR/build/ipa" \
          CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/ipa/*.ipa
      - build/WeatherApp.xcarchive

    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true
